label variable reason_for_or "Reason for OR"
label define reason_for_or 1 "Peritonitis" 2 "Evisceration" 3 "Hemodynamic Instability" 4 "Imaging/DPL" 5 "Concerning Exam"

label variable Agey "Age"
label variable sex_num "Male Sex"
label variable race_num "White Race"
label variable BMI "BMI"
label variable ISS "Injury Severity Score"
label variable EDSBP "Systolic Blood Pressure in ED"
label variable HospLOS "LOS"
label variable number_intraop_transfusions "Number of Intraoperative Transfusions"
label variable number_OR_visits "Number of OR Visits"
label variable RBC1st24hrs "Blood 1st 24 hours (units)"
label variable SSI "Surgical Site Infection"
label variable gu_injury "GU Injury"
label variable vascular_injury "Vascular Injury"
label variable diaphragm_injury "Diaphragm Injury"
label variable spleen_injury "Spleen Injury"
label variable liver_injury "Liver Injury"
label variable kidney_injury "Kidney Injury"
label variable solid_organ_injury "Solid Organ Injury"
label variable traumaticherniarepair "Traumatic Hernia Repair"
label variable cholecystectomy "Cholecystectomy"
label variable mesentericomentalappendagere "Meseteric, omental appendage repair"
label variable dpl "DPL"
label variable dpl_positive "Positive DPL"
label variable ex_lap "Exploratory Laparotomy"
label variable died "Death"
label variable gi_resection "GI Resection"
label variable gi_repair "GI Repair"
label variable gi_repair_resection "GI Resection or Repair"
label variable need_for_reoperation "Reoperation"
